### ISSUE TITLE
New version 1.3.6 does not work with jquery-1.11.3 & jquery-migrate-1.2.1

### ISSUE THREAD

**Issue by EdMueller** [hazzik/livequery#8]
When using the old version 1.0.3, it works fine without errors:

<script src="jquery-1.11.3.min.js"></script>

... jquery-migrate-1.2.1.min.js ...
... jquery.livequery-1.0.3.js ...

But when i use the new version 1.3.6 with

<script src="jquery-1.11.3.min.js"></script>

... jquery-migrate-1.2.1.min.js ...
... jquery.livequery-1.3.6.js ...

, the following error (with and without the migration package) happens:
TypeError: b.call is not a function
...==!1)break}else if(g){for(;f>e;e++)if(d=b.call(a[e],e,a[e]),d===!1)break}else fo...
------------------------------------------------^

With jquery-1.11.3.js it happens here: (Zeile 384, Spalte 13)

Could you check this out?
I use your plugin with this example: N-Level of Dynamic Loading of DropDowns using Ajax and PHP. Part 2 from http://www.99points.info/2010/12/n-level-dynamic-loading-of-dropdowns-using-ajax-and-php/

**Comment by hazzik** [comment]
The overload you're using has been removed from the library due duplicate functionality of [$.live](http://api.jquery.com/live/) / [$.on](http://api.jquery.com/on/) 
see: 20efab24d8a93d653db8f7a35ec1294a5d68d0ae
